// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	MirrorReq
	MirrorResp
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MirrorReq struct {
	A                *string `protobuf:"bytes,1,req,name=a" json:"a,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MirrorReq) Reset()         { *m = MirrorReq{} }
func (m *MirrorReq) String() string { return proto.CompactTextString(m) }
func (*MirrorReq) ProtoMessage()    {}

func (m *MirrorReq) GetA() string {
	if m != nil && m.A != nil {
		return *m.A
	}
	return ""
}

type MirrorResp struct {
	A                *string `protobuf:"bytes,1,req,name=a" json:"a,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MirrorResp) Reset()         { *m = MirrorResp{} }
func (m *MirrorResp) String() string { return proto.CompactTextString(m) }
func (*MirrorResp) ProtoMessage()    {}

func (m *MirrorResp) GetA() string {
	if m != nil && m.A != nil {
		return *m.A
	}
	return ""
}

func init() {
}
