// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	SumReq
	SumResp
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SumReq struct {
	A                *uint32 `protobuf:"varint,1,req,name=a" json:"a,omitempty"`
	B                *uint32 `protobuf:"varint,2,req,name=b" json:"b,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SumReq) Reset()         { *m = SumReq{} }
func (m *SumReq) String() string { return proto.CompactTextString(m) }
func (*SumReq) ProtoMessage()    {}

func (m *SumReq) GetA() uint32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return 0
}

func (m *SumReq) GetB() uint32 {
	if m != nil && m.B != nil {
		return *m.B
	}
	return 0
}

type SumResp struct {
	Sum              *uint32 `protobuf:"varint,1,req,name=sum" json:"sum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SumResp) Reset()         { *m = SumResp{} }
func (m *SumResp) String() string { return proto.CompactTextString(m) }
func (*SumResp) ProtoMessage()    {}

func (m *SumResp) GetSum() uint32 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

func init() {
}
